# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
    vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: 'tsar7'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '(nop$(Build.BuildId))'