# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop
pool:
  name: Dev
  demands:
   - agent.name -equals Dev

steps:
- script: sudo curl -sSL https://get.docker.com/ | sh
  displayName: Docker Install
