# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest


stages:
  - stage: 
    jobs:
    - job: 
      steps:
      - task: DotNetCoreCLI@2
        inputs:
         command: 'build'
         projects: '**/*.sln'
      - task: DotNetCoreCLI@2
        inputs:
         command: 'publish'
         publishWebProjects: true
         zipAfterPublish: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory/**.zip)'
          ArtifactName: 'Nop'
          publishLocation: 'Container'
