# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool: Az-Pool

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'caesar269 / nopcommerce'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'